# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy the rest of the application code
COPY . .

# Build the project using TypeScript
RUN npm run build

# Expose the port if needed (not explicitly required)

# Start the MCP server
CMD ["node", "dist/index.js"]
