name: CI Checks

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Add manual trigger option

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      checks: write  # Added permission for test reporter
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: make test

      - name: Publish Unit Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-results
          path: test-results/test-results.xml
          
      - name: Build Docker image
        run: make docker-build

      - name: Run Docker MCP Test
        run: |
          OUTPUT=$(make docker-test-mcp)
          echo "$OUTPUT"
          # Validate that the output contains expected patterns
          if echo "$OUTPUT" | grep -q '"tools": \[' && echo "$OUTPUT" | grep -q '"name": "create_entities"'; then
            echo "Docker MCP test passed - found expected patterns in output"
          else
            echo "Docker MCP test failed - did not find expected patterns in output"
            exit 1
          fi

      - name: Publish Docker Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: docker-test-results
          path: test-results/docker-test-results.xml

      - name: Mocha Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Mocha Tests            # Name of the check run which will be created
          path: test-results/test-results.xml
          reporter: java-junit         # Format of test results
          fail-on-error: true
          
      - name: Docker Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Docker MCP Tests       # Name of the check run which will be created
          path: test-results/docker-test-results.xml
          reporter: java-junit         # Format of test results
          fail-on-error: true